import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { evaluateBorrower, formatInr, formatLakhs, formatPercent, QUESTION_DEFINITIONS, RULES, SAMPLE_BORROWERS } from './domain/rules'
import './styles.css'

const blank = { name: '', age: 0, city: '', purpose: 'wedding', loanType: 'not-sure', requestedAmount: 500000, incomeType: 'salaried', monthlyIncome: 60000, incomeLow: 40000, incomeHigh: 60000, documentedAnnualIncome: 0, existingEmi: 0, otherHouseholdIncome: 0, monthlyExpenses: null, creditScore: null, collateralValue: 0, expensesKnown: false, recentBounce: false, highCostDebt: false, tenureMonths: 48 }
const asValue = (key, value) => {
  if (['expensesKnown', 'recentBounce', 'highCostDebt'].includes(key)) return value === 'true'
  if (key === 'creditScore' || key === 'monthlyExpenses') return value === '' ? null : Number(value)
  if (['collateralValue', 'requestedAmount', 'monthlyIncome', 'incomeLow', 'incomeHigh', 'documentedAnnualIncome', 'existingEmi', 'otherHouseholdIncome', 'tenureMonths', 'age'].includes(key)) return value === '' ? 0 : Number(value)
  return value
}

function QuestionField({ question, profile, update }) {
  return <label className="field" key={question.id}><span>{question.label}{question.optional && <small> optional</small>}</span>{question.type === 'select' ? <select value={String(profile[question.id] ?? '')} onChange={(event) => update(question.id, event.target.value)}>{question.options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : <div className="input-wrap">{question.prefix && <b>{question.prefix}</b>}<input type="number" min={question.min ?? 0} max={question.max} value={profile[question.id] ?? ''} onChange={(event) => update(question.id, event.target.value)} placeholder="Not provided" /></div>}<small className="affects">Affects {question.affects}</small></label>
}

function App() {
  const [profile, setProfile] = useState(blank)
  const [stage, setStage] = useState('intro')
  const result = useMemo(() => evaluateBorrower(profile), [profile])
  const visibleQuestions = QUESTION_DEFINITIONS.filter((question) => !question.visible || question.visible(profile))
  const mustQuestions = visibleQuestions.filter((question) => question.tier === 'must')
  const additionalQuestions = visibleQuestions.filter((question) => question.tier === 'additional')
  const update = (key, value) => setProfile((current) => ({ ...current, [key]: asValue(key, value) }))
  const loadSample = (name) => { setProfile({ ...blank, ...SAMPLE_BORROWERS[name] }); setStage('form') }
  const reset = () => { setProfile(blank); setStage('intro') }

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">B</span><span>Borrower <i>Copilot</i></span></div><div className="top-note">Private, local, illustrative</div></header>
    {stage === 'intro' && <main className="intro-page">
      <div className="kicker">A decision workspace for Indian borrowers</div>
      <h1>Before you borrow, know what you can <em>carry.</em></h1>
      <p className="intro-copy">A clear self-assessment for the conversation before the lender conversation. We will show what a lender may size, what is safer for you, and where the uncertainty lives.</p>
      <button className="primary-button" onClick={() => setStage('form')}>Start with your numbers <span>↗</span></button>
      <div className="promise-row"><span><b>01</b> Borrow or pause</span><span><b>02</b> A safe range</span><span><b>03</b> Your negotiation card</span></div>
      <section className="sample-section"><div><div className="section-label">See the model in motion</div><h2>Try one of the three challenge borrowers</h2><p>These are illustrative profiles from the brief. They are prefilled so you can inspect the reasoning without entering every number.</p></div><div className="sample-list">{Object.keys(SAMPLE_BORROWERS).map((name) => <button key={name} className="sample-button" onClick={() => loadSample(name)}><span><b>{name}</b><small>{SAMPLE_BORROWERS[name].purpose === 'business' ? 'Business growth' : SAMPLE_BORROWERS[name].purpose === 'vehicle' ? 'Electric scooter' : 'Wedding loan'}</small></span><span>→</span></button>)}</div></section>
    </main>}
    {stage === 'form' && <main className="workspace"><div className="progress"><span>YOUR PICTURE</span><div><i className="active"/><i/><i/></div><span>1 / 3</span></div><div className="workspace-heading"><div className="kicker">Start with the minimum picture</div><h1>What would make this borrowing <em>wise?</em></h1><p>The first questions are enough to produce all four outputs. Extra questions are optional and only appear when they can tighten an answer. Unknown information stays unknown; it never quietly becomes zero.</p></div><div className="form-layout"><section className="question-panel"><div className="section-label">Must answer</div><div className="question-grid">{mustQuestions.map((question) => <QuestionField key={question.id} question={question} profile={profile} update={update} />)}</div>{additionalQuestions.length > 0 && <details className="additional-questions"><summary>Improve the estimate with more details</summary><p>Each of these changes a number, the route, the decision, or the confidence. You can leave them unanswered.</p><div className="question-grid">{additionalQuestions.map((question) => <QuestionField key={question.id} question={question} profile={profile} update={update} />)}</div></details>}<div className="form-actions"><button className="quiet-button" onClick={reset}>Start over</button><button className="primary-button" onClick={() => setStage('result')}>See my assessment <span>↗</span></button></div></section><aside className="live-preview"><div className="section-label">Live preview</div><div className="preview-number">{formatLakhs(result.safeAmount)}</div><p>borrower-safe amount to plan around</p><div className="preview-line"><span>Borrower-safe EMI ceiling</span><b>{formatInr(result.recommendedEmi)}</b></div><div className="preview-line"><span>Borrower-safe amount</span><b>{formatLakhs(result.safeAmount)}</b></div><div className="preview-line"><span>Confidence</span><b>{result.confidence.level}</b></div><div className="preview-note">Updates as you answer. This is a planning estimate, not an approval.</div></aside></div></main>}
    {stage === 'result' && <Result profile={profile} result={result} onBack={() => setStage('form')} onReset={reset} />}
  </div>
}

function Result({ profile, result, onBack, onReset }) {
  const [quote, setQuote] = useState('')
  const decisionClass = result.decision === 'BORROW' ? 'good' : result.decision === 'BORROW LESS' ? 'caution' : 'stop'
  return <main className="result-page"><div className="result-toolbar"><button className="text-button" onClick={onBack}>← Edit answers</button><button className="text-button" onClick={() => window.print()}>Print card ↗</button></div><section className={`decision-band ${decisionClass}`}><div><div className="kicker">Your first answer</div><h1>{result.decision.toLowerCase().replace('’', "'")}</h1><p>{result.decisionReason}</p></div><div className="confidence"><span>Confidence</span><b>{result.confidence.level}</b><small>{result.confidence.reason}</small></div></section><section className="result-grid"><div className="main-result"><div className="section-label">The four numbers to take with you</div><div className="amount-compare"><Metric label="You asked for" value={formatLakhs(result.requested)} detail="Your stated amount, not a recommendation."/><Metric label="Estimated lender-side capacity" value={formatLakhs(result.lenderAmount)} detail={`${formatInr(result.affordability.lenderAvailable)} new EMI at ${RULES.lenderFoir * 100}% of normalized borrower income.`}/><Metric label="Borrower-safe amount" value={formatLakhs(result.safeAmount)} detail={`${formatInr(result.recommendedEmi)} monthly EMI ceiling after the ${RULES.safeFoir * 100}% safe FOIR rule.`}/><Metric emphasis label="Practical amount — use this for planning" value={formatLakhs(result.safeAmount)} detail="Use this amount as your personal planning ceiling."/></div><div className="why-block"><div className="section-label">Why this answer</div>{result.explanation.map((line) => <p key={line}>↳ {line}</p>)}</div><div className="detail-grid"><article><div className="section-label">Fair rate range</div><strong className="big-mono">{formatPercent(result.rate.min)}–{formatPercent(result.rate.max)}</strong><p>{result.rate.reason}</p></article><article><div className="section-label">All-in APR estimate</div><strong className="big-mono">{formatPercent(result.apr.min)}–{formatPercent(result.apr.max)}</strong><p>Includes a {formatPercent(RULES.processingFee * 100)} prototype processing fee of about {formatInr(result.apr.fee)} on the practical amount.</p></article><article><div className="section-label">Product route</div><strong>{result.route.product}</strong><p>{result.route.reason}</p></article><article><div className="section-label">Stress case</div><strong>{result.stress.survives ? 'Still carries' : 'Buffer breaks'}</strong><p>With borrower income down {RULES.stressIncomeDrop * 100}% and the rate up {RULES.stressRateIncrease * 100} points, requested EMI is {formatInr(result.stress.requestedEmi)} against {formatInr(result.stress.safeAvailable)} safe room.</p></article></div><TenureTradeoff result={result} /></div><NegotiationCard result={result} quote={quote} setQuote={setQuote} /></section><button className="quiet-button bottom-reset" onClick={onReset}>Assess another situation</button></main>
}

function TenureTradeoff({ result }) {
  return <section className="tenure-tradeoff"><div className="section-label">Tenure trade-off</div><p>Shorter tenure means a higher EMI but less total interest. Longer tenure lowers the EMI but costs more interest. These figures use the borrower-safe amount at the rate midpoint.</p><div className="tenure-table"><div className="tenure-row tenure-head"><span>Tenure</span><span>EMI</span><span>Total interest</span></div>{result.tenureTradeoff.map((option) => <div className={`tenure-row ${option.isSelected ? 'selected' : ''}`} key={option.months}><span>{option.months} months{option.isSelected ? ' · selected' : ''}</span><span>{formatInr(option.emi)}</span><span>{formatInr(option.totalInterest)}</span></div>)}</div></section>
}

function Metric({ label, value, detail, emphasis }) { return <div className={`metric ${emphasis ? 'emphasis' : ''}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function NegotiationCard({ result, quote, setQuote }) {
  const quoteNumber = Number(quote)
  const quoteMessage = quoteNumber > result.rate.max ? `Ask why ${quote}% is above your illustrative benchmark.` : quoteNumber < result.rate.min ? `This is below your illustrative benchmark. Check the full quote and fees before comparing.` : `This quote is within your illustrative benchmark. Compare the APR and fees too.`
  const cardAmountLabel = result.decision === 'DON’T BORROW' ? 'Safe amount if you revisit later' : 'Recommended amount'
  return <aside className="negotiation-card"><div className="card-top"><span className="brand-mark small">B</span><span>Negotiation Card</span><span className="card-date">LOCAL / PRIVATE</span></div><h2>What I should carry into the lender conversation.</h2><div className="card-hero"><span>{cardAmountLabel}</span><strong>{formatLakhs(result.safeAmount)}</strong><small>{result.decisionReason}</small></div><div className="card-rows"><div><span>Lender-side estimate</span><b>{formatLakhs(result.lenderAmount)}</b></div><div><span>Borrower-safe amount</span><b>{formatLakhs(result.safeAmount)}</b></div><div><span>Fair rate</span><b>{formatPercent(result.rate.min)}–{formatPercent(result.rate.max)}</b></div><div><span>APR incl. fee</span><b>{formatPercent(result.apr.min)}–{formatPercent(result.apr.max)}</b></div><div><span>EMI ceiling</span><b>{formatInr(result.recommendedEmi)}</b></div><div><span>Route</span><b>{result.route.product}</b></div></div><div className="quote-check"><label>Compare a lender quote<input value={quote} onChange={(event) => setQuote(event.target.value)} placeholder="e.g. 14" type="number" min="0" step="0.1" /><span>%</span></label>{quote && <p className={quoteNumber > result.rate.max ? 'quote-high' : quoteNumber < result.rate.min ? 'quote-low' : 'quote-ok'}>{quoteMessage}</p>}</div><div className="card-foot">Illustrative self-assessment only. Actual underwriting, pricing and fees vary by lender.</div></aside>
}

createRoot(document.getElementById('root')).render(<App />)
